site_name: $$REPO$$ Documentation
repo_url: https://github.com/$$OWNER$$/$$REPO$$
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.code.copy
nav:
  - Home: "index.md"
